name: Build Calendars

on:
  workflow_dispatch:
    inputs:
      cadence:
        description: 'Cadence'
        required: true
        default: 'manual'
        type: choice
        options:
          - manual
          - weekly
          - monthly
  push:
    paths:
      - 'build_calendars.py'
      - 'requirements.txt'
      - '.github/workflows/build-calendars.yml'
  schedule:
    # Uncomment the line below to enable weekly rebuilds (runs every Sunday at midnight UTC)
    # - cron: '0 0 * * 0'
    # Uncomment the line below to enable monthly rebuilds (runs on the 1st of every month at midnight UTC)
    # - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CSV_URL: https://docs.google.com/spreadsheets/d/e/2PACX-1vRwoBRBFI-z4haeZv0WMruMzGmebRVPIa-pYOzbMVBX9Si9iQa8VMBzkoYjWt8VRck6OB9853xSSPzM/pub?gid=0&single=true&output=csv
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test versions
        run: |
          python -c "import pandas, ics, openpyxl; print(f'pandas {pandas.__version__}, ics {ics.__version__}, openpyxl {openpyxl.__version__}')"

      - name: Run build
        run: python build_calendars.py
        env:
          CSV_URL: ${{ env.CSV_URL }}

      - name: Check if ICS files exist
        run: |
          if [ -z "$(ls public/calendars/*.ics 2>/dev/null)" ]; then
            echo "No ICS files generated. Failing."
            exit 1
          else
            echo "ICS files generated."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
